# Generated by Django 5.2.5 on 2025-11-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_favorite_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pic_path",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("nonfiction", "Non-fiction"),
                    ("children", "Children's Books"),
                    ("classic", "Classics"),
                    ("education", "Education"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishdate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="web",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
